dist: trusty
language: node_js
node_js:
  - "14.15.3"

os:
  - linux
addons:
  apt:
    update: true
before_install:
  - npm install -g yarn

jobs:
  include:
    - stage: lint
      script:
        - ng lint
    - stage: build & publish
      script:
        - yarn run build:prod
      deploy:
        - provider: pages
          token: $GH_TOKEN
          local_dir: dist
          verbose: true
          edge: true
        - provider: script
          token: $GH_TOKEN
          skip_cleanup: true
          script: npx semantic-release
      if: branch = master
